name: Build and Push to GAR

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.WIZ_LABS_GCP }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-docker.pkg.dev # Replace with your GAR region and domain
          username: _json_key
          password: ${{ secrets.WIZ_LABS_GCP }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Path to your Dockerfile, relative to the repository root
          push: true
          tags: us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cicd-testing/test-image:latest # Replace with your details
          cache-from: type=gha
          cache-to: type=gha,mode=max
